### ISSUE TITLE
gray overlay in pdf view

### ISSUE THREAD

**Issue by wiesoauch** [tobealive/logseq-allday-theme#12] opened 2022-08-14 10:28 UTC
### Description
- pdf has a gray overlay when opened with standard settings in dark version of the theme
- the pdf is displayed normally when opened in the light version of the theme

### Screenshots
- the gray overlay only appears in the "white" view of the pdf
<img width="567" alt="Bildschirmfoto 2022-08-11 um 15 35 36" src="https://user-images.githubusercontent.com/24652279/184530157-e38bb4b6-7ceb-4ff2-96e0-b80b91e2d505.png">
- if "sepia" or "dark blue" is chosen under "more settings" the pdf is displayed as expected
<img width="588" alt="Bildschirmfoto 2022-08-11 um 15 36 00" src="https://user-images.githubusercontent.com/24652279/184530162-6361bdba-2f0f-4ff1-92b2-62e35f1d519e.png">
<img width="564" alt="Bildschirmfoto 2022-08-11 um 15 35 49" src="https://user-images.githubusercontent.com/24652279/184530165-18f3ab76-22ec-412c-a76b-c5fa349ed701.png">

Thanks for the beautiful and clean theme!

**Comment by tobealive** [comment] 2022-08-14 16:09
Hey thanks for making me aware of this. 

It's very likely the issue mentioned in #11. As yours comes with screenshots and description I know what to look for 🧐☺️. I'll take some time this evening to investigate. Have a good day!

**Comment by tobealive** [comment] 2022-08-14 16:57
Should be fixed in the new version. Please let me know if theres something else.

**Comment by JuliDi** [comment] 2022-08-15 07:35
@tobealive the issue seems fixed now, thank you!
However the toolbar background looks a bit weird now (or still?) on the very left side.

![Screenshot 2022-08-15 at 09 33 08](https://user-images.githubusercontent.com/20155974/184594537-b9caf294-c641-44ba-ae32-cb95d00241c0.png)

**Comment by tobealive** [comment] 2022-08-15 15:25
I've thrown an update on it. Let me how how it is on your machine. Currently I don't have an apple machine at hands.

**Comment by JuliDi** [comment] 2022-08-15 15:34
The issue is fixed now, thanks a lot!

**Closed** 2022-08-15 15:58 UTC
