### ISSUE TITLE
连接线的问题，界面一点点的小遗憾。

### ISSUE THREAD

**Issue by kubulo** [tobealive/logseq-allday-theme#15] opened 2022-09-06 13:59 UTC
<img width="302" alt="Snipaste_2022-09-06_21-57-43" src="https://user-images.githubusercontent.com/74105898/188654683-d9f87d18-3d17-4eae-a2fa-6bc61347a6f5.png">
就是竖线位置有细微错位的地方。

**Comment by tobealive** [comment] 2022-09-07 08:55
Hey @kubulo 

Thank you for reporting the issue! It must have been introduced with one of the recent logseq updates. There were similar issues with new versions breaking the bullet threading like this in the past. 

I'm looking into this and doing my best with a quick fix today or tomorrow!

**Comment by tobealive** [comment] 2022-09-08 19:38
Hey again @kubulo,

I'm not able to reproduce this issue. Checked on two systems and screens with different resolutions.  I tried with different levels of indentation, also adding Chinese characters.

Are you using the latest version of logseq and the theme (currently it's `1.1.15`)? I found the integrated `check update` function in logseq sometimes doesn't pull updates. You can try uninstalling and reinstalling the theme from the marketplace in that case.

**Comment by tobealive** [comment] 2022-12-24 14:29
This doesn't seem to be an issue anymore, so I'm closing it. Please leave a word if you still notice the problems, then we will open it again and tackle them 💪

**Closed by tobealive** 2022-12-24 14:29 UTC
